// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ulixes-bloom/ya-gophkeeper/internal/infrastructure/proto/gen (interfaces: SecretService_GetLatestSecretStreamServer)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pb "github.com/ulixes-bloom/ya-gophkeeper/internal/infrastructure/proto/gen"
	metadata "google.golang.org/grpc/metadata"
)

// MockSecretService_GetLatestSecretStreamServer is a mock of SecretService_GetLatestSecretStreamServer interface.
type MockSecretService_GetLatestSecretStreamServer struct {
	ctrl     *gomock.Controller
	recorder *MockSecretService_GetLatestSecretStreamServerMockRecorder
}

// MockSecretService_GetLatestSecretStreamServerMockRecorder is the mock recorder for MockSecretService_GetLatestSecretStreamServer.
type MockSecretService_GetLatestSecretStreamServerMockRecorder struct {
	mock *MockSecretService_GetLatestSecretStreamServer
}

// NewMockSecretService_GetLatestSecretStreamServer creates a new mock instance.
func NewMockSecretService_GetLatestSecretStreamServer(ctrl *gomock.Controller) *MockSecretService_GetLatestSecretStreamServer {
	mock := &MockSecretService_GetLatestSecretStreamServer{ctrl: ctrl}
	mock.recorder = &MockSecretService_GetLatestSecretStreamServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretService_GetLatestSecretStreamServer) EXPECT() *MockSecretService_GetLatestSecretStreamServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockSecretService_GetLatestSecretStreamServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockSecretService_GetLatestSecretStreamServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockSecretService_GetLatestSecretStreamServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m *MockSecretService_GetLatestSecretStreamServer) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockSecretService_GetLatestSecretStreamServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockSecretService_GetLatestSecretStreamServer)(nil).RecvMsg), arg0)
}

// Send mocks base method.
func (m *MockSecretService_GetLatestSecretStreamServer) Send(arg0 *pb.GetSecretChunkResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSecretService_GetLatestSecretStreamServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSecretService_GetLatestSecretStreamServer)(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockSecretService_GetLatestSecretStreamServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockSecretService_GetLatestSecretStreamServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockSecretService_GetLatestSecretStreamServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m *MockSecretService_GetLatestSecretStreamServer) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockSecretService_GetLatestSecretStreamServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockSecretService_GetLatestSecretStreamServer)(nil).SendMsg), arg0)
}

// SetHeader mocks base method.
func (m *MockSecretService_GetLatestSecretStreamServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockSecretService_GetLatestSecretStreamServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockSecretService_GetLatestSecretStreamServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockSecretService_GetLatestSecretStreamServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockSecretService_GetLatestSecretStreamServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockSecretService_GetLatestSecretStreamServer)(nil).SetTrailer), arg0)
}
